version: "3.9"

services:

  api:
    container_name: user-api
    build: .
    ports:
      - 5000:5000
    networks:
      - public
    restart: on-failure
    depends_on:
      - db
      - mongo
    environment:
      NODE_ENV: production
      DATABASE_DB: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db
      PORT: 5000
      MONGO_HOST: mongo
      MONGO_DATABASE_USER: mongo
      MONGO_DATABASE_DB: mongo

  migration:
    container_name: migration
    build: db
    networks:
      - public
    restart: on-failure
    depends_on:
      - db
    environment:
      DATABASE_DB: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: db

  db:
    container_name: pg.db
    image: postgres
    ports:
      - 5432:5432
    networks:
      - public
    restart: on-failure
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mongo:
    container_name: mongo.db
    image: mongo
    ports:
      - 27017:27017
    networks:
      - public
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  mongo-express:
    container_name: mongo.admin
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - public
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongo:mongo@mongo:27017/

networks:
  public:
